apiVersion: apps/v1
kind: Deployment
metadata:
  name: dashapi
  labels:
    app: dashapi
spec:
  selector:
    matchLabels:
      app: dashapi
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  progressDeadlineSeconds: 1200
  minReadySeconds: 60
  template:
    metadata:
      labels:
        app: dashapi
    spec:
      terminationGracePeriodSeconds: 60
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: "app"
                operator: In
                values:
                - dashapi
              - key: "temporary"
                operator: In
                values:
                - "true"
            topologyKey: "kubernetes.io/hostname"
      containers:
      - name: udacity
        image: dashnum/dash-uda-4
        command: [
          "/bin/bash", 
          "-c", 
          "npm run serve"
          ]
        imagePullPolicy: Always
        resources:
          limits:
            memory: 64Mi
            cpu: 250m
          requests:
            memory: 32Mi
            cpu: 200m
        ports:
        - containerPort: 9080
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /
            scheme: HTTP
            port: 9080
          periodSeconds: 10
          successThreshold: 1
          failureThreshold: 2
          timeoutSeconds: 1

apiVersion: v1
kind: Service
metadata:
  name: dashapi
spec:
  type: LoadBalancer
  selector:
    app: dashapi
  ports:
    - name: http
      protocol: TCP
      port: 9080
      targetPort: 9080
    - name: https
      protocol: TCP
      port: 443
      targetPort: 443

kind: HorizontalPodAutoscaler
apiVersion: autoscaling/v1
metadata:
  name: dashapi
spec:
  scaleTargetRef:
    apiVersion: extensions/v1beta1
    kind: Deployment
    name: dashapi
  minReplicas: 2
  maxReplicas: 5
  targetCPUUtilizationPercentage: 80



 


