# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2
jobs:
  build:
# docker:
#   # Use the same Docker base as the project
#   - image: python:3.7.3-stretch

# wget http://security.ubuntu.com/ubuntu/pool/main/a/apt/apt_1.0.1ubuntu2.17_amd64.deb -O apt.deb
# pkexec dpkg -i apt.deb
    machine: true
    working_directory: ~/repo
    steps:
      - checkout          
      - run:
          name: install dependencies
          command: |
            wget http://www.python.org/ftp/python/3.3.5/Python-3.3.5.tar.xz
            tar xJf ./Python-3.3.5.tar.xz
            cd ./Python-3.3.5
            ./configure --prefix=/opt/python3.3
            make && make install

            python3 -m venv venv
            . venv/bin/activate
            make install
            wget -O /bin/hadolint https://github.com/hadolint/hadolint/releases/download/v1.16.3/hadolint-Linux-x86_64 &&\
            chmod +x /bin/hadolint
            
      - run:
          name: install additional stuff
          command: |
            wget https://github.com/instrumenta/kubeval/releases/latest/download/kubeval-linux-amd64.tar.gz
            tar xf kubeval-linux-amd64.tar.gz
            cp kubeval /usr/local/bin      

      - run:
          name: run lint
          command: |
            . venv/bin/activate
            make lint 

      - run:
          name: Build and push docker image
          command: |
            docker build -t dashapi .
            docker tag dashapi dashnum/dash-uda-4
            docker login --username $DOCKERUSERNAME --password $DOCKERPASS
            docker push dashnum/dash-uda-4