# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#

version: 2.1
orbs:
  aws-cli: circleci/aws-cli@0.1.19
  slack: circleci/slack@3.4.2
  aws-eks: circleci/aws-eks@0.2.3
  kubernetes: circleci/kubernetes@0.4.0
  docker: circleci/docker@1.5.0

jobs:
  build:
    docker:
      # Use the same Docker base as the project
      - image: circleci/python:3.6.1

    working_directory: ~/repo
    steps:
      - checkout
    # Build Docker image
      - run:
          name: Build and deploy docker image
          command: |
            systemctl start docker
            service docker start
            chmod +x build_and_push_docker.sh
            docker login --username $DOCKERUSERNAME --password $DOCKERPASS
            ./build_and_push_docker.sh

    # Create EKS cluster
      - run:
          name: Create EKS cluster
          command: |
            ./create_cluster.sh

    # Deploy docker image to EKS cluster
      - run:
          name: Deploy EKS image
          command: |
            ./run_kubernetes.sh

    # Cleanup
      - run:
          name: Cleanup
          command: |
            eksctl delete cluster prod